spring.application.name=BLOB_backend
spring.datasource.url=jdbc:mariadb://218.234.33.15:3356/cms
spring.datasource.username=cms_admin
spring.datasource.password=1q2w3e4r!@#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true